# Generated by Django 5.0.4 on 2024-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0012_rename_datas_medico_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_datas',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
